FROM debian:9

ARG JENKINS_GROUP_ID=200
ARG JENKINS_USER_ID=200

RUN groupadd --gid $JENKINS_GROUP_ID jenkins && \
    useradd --uid $JENKINS_USER_ID --gid $JENKINS_GROUP_ID --create-home jenkins

RUN apt-get update && \
    apt-get install -y curl openjdk-8-jdk postgresql-client

ADD https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-linux-bin.tar.gz /var/soapui/SoapUI-5.4.0-linux-bin.tar.gz

RUN tar -xzf /var/soapui/SoapUI-5.4.0-linux-bin.tar.gz -C /var/soapui

COPY docker/entrypoint-script.sh /entrypoint-script.sh

ENTRYPOINT [ "/entrypoint-script.sh" ]
